services:
  website:
    image: nginx:alpine
    container_name: jessma-website
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    ports:
      - "9876:80"
    restart: unless-stopped
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true