services:
  website:
    build: .
    container_name: jessma-website
    ports:
      - "9876:80"
    restart: unless-stopped
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true